//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WormHole.java
//  @ Date : 2016.03.27.
//  @ Author : 
//
//

public class WormHole {
	private Coord BluePortal;
	private Coord YellowPortal;
	
	//ha bevan allitva kek es sarga portal akkor igazat ad vissza
	//BluePortal es YellowPortal beállitasa kivulrol - Bullet osztalybol
	//vigyazni kell a null beíllitasara ha megszunik a portal
	public Boolean isOpen() {
		System.out.println("WormHole: isOpen metódus hívás");
		if (BluePortal!= null && YellowPortal != null)
			return true;
		else 
			return false;
	}
	
	//BluePortal koordiatait adja vissza
	public Coord getBlue() {
		System.out.println("WormHole: getBlue metódus hívás");
		return BluePortal;
	}
	
	//YellowPortal koordinatait adja vissza
	public Coord getYellow() {
		System.out.println("WormHole: getYellow metódus hívás");
		return YellowPortal;
	}
	
	//YellowPortal koordinatait allitja be 
	public void setBlue(Coord c) {
		System.out.println("WormHole: setBlue metódus hívás");
		BluePortal = c;
	}
	
	//YellowPortal koordinatait allitja be
	public void setYellow(Coord c) {
		System.out.println("WormHole: setYellow metódus hívás");
		YellowPortal = c;
	}
}
