//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Wall.java
//  @ Date : 2016.03.27.
//  @ Author : 
//
//



//Osztály a fal típusú mezõ kezelésére
public class Wall extends Tile {
	
	//Megmondja, hogy ONeil mit csináljon, ha falra akar lépni
	public Wall (Coord c) {
		super(c);
	}
	
	@Override
	 public boolean fly(Bullet b)
	 {
		 System.out.println("Wall: bang bang falba ütköztem");
		 return false;
	 }
	
	@Override
	public Coord stepOn(Coord k) {
		System.out.println("Wall: stepOn metódus hívás, ONeil nem tud erre a mezõre, marad az eredeti helyén");
		return k;
	}

	

}
